### ISSUE TITLE
Remove empty gem?

### ISSUE THREAD

**Issue by ForeverZer0** [taroxd/RGSS#3]
I have developed a cross-platform implementation of RGSS as a C-extension that will natively run XP, VX, and VXAce, and `rgss` would be the most appropriate name for it. I noticed you reserved that namespace nearly 5 years ago, and have never updated it, so I am assuming the project is abandoned? 

if so, would it be possible to `gem yank` to free up the name? If not, totally understandable, just figured I would ask before attempting to devise another name that is less intuitive.

**Comment by taroxd** [comment]
Yanked. Sorry for the inconvenience.

**Comment by ForeverZer0** [comment]
No inconvenience at all, very much appreciated, thank you so much!

**Comment by ForeverZer0** [comment]
Sorry to be annoying, but still not letting me push because of ownership for some reason...

If you get a chance, could you possibly `gem owner rgss --add efreed09@gmail.com`.
Not sure the cause, maybe temporary cache issue or something.

**Comment by taroxd** [comment]
I add you as owner so that you do not need to wait for 100 more days :)
